channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip=20.1.1
  - pip:
    - azureml-sdk==1.51.0
    - azureml-core==1.51.0
    - azureml-contrib-services==1.51.0
    - azureml-monitoring
    - azureml-inference-server-http
    - azureml-pipeline==1.51.0
    - file-read-backwards==3.0.0
    - ipykernel==6.28.0
    - matplotlib==3.2.1
    - numpy==1.21.6
    - pandas==1.1.5
    - psycopg2-binary==2.9.5
    - scikit-learn==0.22.1
    - SQLAlchemy==1.4.6
    - xgboost==1.3.3
    - azureml-telemetry==1.51.0
    - cryptography==41.0.5